/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dbproject;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class SignUpForm extends javax.swing.JFrame {

    /**
     * Creates new form SignUpForm
     */
    DatabaseHandler ob = new DatabaseHandler();
    
    private String user, pass, dbName, fname, lname, rpass, email, query, area, usertype;
    ResultSet result;
    public SignUpForm() {
        initComponents();
        
        user = "root";
        pass = "";
        dbName = "electroarena2";
        ob.setConnection(dbName, user, pass);
        userInfo.removeAllItems();
        String[] usertype = ob.getuserType();
        userInfo.addItem("");
        for(int i=0; i<4; i++){
            userInfo.addItem(usertype[i]);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        signupPanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jSeparator12 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jSeparator13 = new javax.swing.JSeparator();
        jPanel5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jSeparator14 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jSeparator15 = new javax.swing.JSeparator();
        jSeparator16 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        jSeparator17 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        jSeparator18 = new javax.swing.JSeparator();
        signupRpass = new javax.swing.JPasswordField();
        signupPass = new javax.swing.JPasswordField();
        signupLname = new javax.swing.JTextField();
        signupFname = new javax.swing.JTextField();
        signupEmail = new javax.swing.JTextField();
        signup = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        signupArea = new javax.swing.JPasswordField();
        jSeparator19 = new javax.swing.JSeparator();
        signinPanel = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jSeparator20 = new javax.swing.JSeparator();
        jSeparator21 = new javax.swing.JSeparator();
        jPanel7 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jSeparator24 = new javax.swing.JSeparator();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jSeparator25 = new javax.swing.JSeparator();
        jSeparator26 = new javax.swing.JSeparator();
        jLabel26 = new javax.swing.JLabel();
        jSeparator27 = new javax.swing.JSeparator();
        jLabel27 = new javax.swing.JLabel();
        jSeparator28 = new javax.swing.JSeparator();
        signinEmail = new javax.swing.JTextField();
        signinPass = new javax.swing.JPasswordField();
        jLabel21 = new javax.swing.JLabel();
        userInfo = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        signin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        signupPanel.setBackground(new java.awt.Color(97, 212, 195));
        signupPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("FIRST NAME");
        signupPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 80, 20));

        jSeparator9.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator9.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        signupPanel.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 320, 10));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("LAST NAME");
        signupPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 80, 20));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("EMAIL");
        signupPanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 50, 20));

        jSeparator10.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator10.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        signupPanel.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 320, 10));

        jSeparator11.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator11.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        signupPanel.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 320, 10));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("REPEAT PASSWORD");
        signupPanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 130, 20));

        jSeparator12.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator12.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        signupPanel.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 320, 10));

        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("PASSWORD");
        signupPanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 100, 20));

        jSeparator13.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator13.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        signupPanel.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 320, 10));

        jPanel5.setBackground(new java.awt.Color(36, 47, 85));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("FIRST NAME");
        jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 80, 20));

        jSeparator14.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator14.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel5.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 320, 10));

        jLabel14.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("LAST NAME");
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 80, 20));

        jLabel15.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("EMAIL");
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 50, 20));

        jSeparator15.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator15.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel5.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 320, 10));

        jSeparator16.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator16.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel5.add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 320, 10));

        jLabel16.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("PASSWORD");
        jPanel5.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, 100, 20));

        jSeparator17.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator17.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel5.add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 570, 320, 10));

        jLabel17.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("PASSWORD");
        jPanel5.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 100, 20));

        jSeparator18.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator18.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel5.add(jSeparator18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 320, 10));

        signupPanel.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, 430, -1));

        signupRpass.setBackground(new java.awt.Color(97, 212, 195));
        signupRpass.setForeground(new java.awt.Color(255, 255, 255));
        signupRpass.setBorder(null);
        signupPanel.add(signupRpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 320, 30));

        signupPass.setBackground(new java.awt.Color(97, 212, 195));
        signupPass.setForeground(new java.awt.Color(255, 255, 255));
        signupPass.setBorder(null);
        signupPass.setCaretColor(new java.awt.Color(255, 255, 255));
        signupPass.setSelectionColor(new java.awt.Color(255, 255, 255));
        signupPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupPassActionPerformed(evt);
            }
        });
        signupPanel.add(signupPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 320, 30));

        signupLname.setBackground(new java.awt.Color(97, 212, 195));
        signupLname.setForeground(new java.awt.Color(255, 255, 255));
        signupLname.setBorder(null);
        signupPanel.add(signupLname, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 320, 30));

        signupFname.setBackground(new java.awt.Color(97, 212, 195));
        signupFname.setForeground(new java.awt.Color(255, 255, 255));
        signupFname.setBorder(null);
        signupFname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupFnameActionPerformed(evt);
            }
        });
        signupPanel.add(signupFname, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 320, 30));

        signupEmail.setBackground(new java.awt.Color(97, 212, 195));
        signupEmail.setForeground(new java.awt.Color(255, 255, 255));
        signupEmail.setBorder(null);
        signupEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupEmailActionPerformed(evt);
            }
        });
        signupPanel.add(signupEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 320, 30));

        signup.setBackground(new java.awt.Color(36, 47, 85));
        signup.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        signup.setForeground(new java.awt.Color(204, 204, 204));
        signup.setText("SIGN UP");
        signup.setBorderPainted(false);
        signup.setContentAreaFilled(false);
        signup.setOpaque(false);
        signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupActionPerformed(evt);
            }
        });
        signupPanel.add(signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, 178, -1));

        jPanel1.setBackground(new java.awt.Color(36, 47, 85));
        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 178, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );

        signupPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, 180, 40));

        jLabel18.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("AREA");
        signupPanel.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 130, 20));

        signupArea.setBackground(new java.awt.Color(97, 212, 195));
        signupArea.setForeground(new java.awt.Color(255, 255, 255));
        signupArea.setBorder(null);
        signupPanel.add(signupArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 320, 30));

        jSeparator19.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator19.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        signupPanel.add(jSeparator19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, 320, 10));

        getContentPane().add(signupPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 600));

        signinPanel.setBackground(new java.awt.Color(36, 47, 85));
        signinPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(204, 204, 204));
        jLabel20.setText("SIGN IN AS ");
        signinPanel.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 110, 50));

        jSeparator20.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator20.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator20.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        signinPanel.add(jSeparator20, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 320, 10));

        jSeparator21.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator21.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator21.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        signinPanel.add(jSeparator21, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 320, 10));

        jPanel7.setBackground(new java.awt.Color(36, 47, 85));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("FIRST NAME");
        jPanel7.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 80, 20));

        jSeparator24.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator24.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel7.add(jSeparator24, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 320, 10));

        jLabel24.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("LAST NAME");
        jPanel7.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 80, 20));

        jLabel25.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("EMAIL");
        jPanel7.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 50, 20));

        jSeparator25.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator25.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel7.add(jSeparator25, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 320, 10));

        jSeparator26.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator26.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel7.add(jSeparator26, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 320, 10));

        jLabel26.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("PASSWORD");
        jPanel7.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, 100, 20));

        jSeparator27.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator27.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel7.add(jSeparator27, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 570, 320, 10));

        jLabel27.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("PASSWORD");
        jPanel7.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 100, 20));

        jSeparator28.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator28.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel7.add(jSeparator28, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 320, 10));

        signinPanel.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, 430, -1));

        signinEmail.setBackground(new java.awt.Color(36, 47, 85));
        signinEmail.setForeground(new java.awt.Color(204, 204, 204));
        signinEmail.setBorder(null);
        signinPanel.add(signinEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 320, 30));

        signinPass.setBackground(new java.awt.Color(36, 47, 85));
        signinPass.setForeground(new java.awt.Color(255, 255, 255));
        signinPass.setBorder(null);
        signinPanel.add(signinPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 320, 30));

        jLabel21.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(204, 204, 204));
        jLabel21.setText("EMAIL");
        signinPanel.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 50, 20));

        userInfo.setBackground(new java.awt.Color(36, 47, 85));
        userInfo.setForeground(new java.awt.Color(240, 240, 240));
        userInfo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        userInfo.setBorder(null);
        userInfo.setOpaque(false);
        signinPanel.add(userInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 90, 30));

        jLabel19.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(204, 204, 204));
        jLabel19.setText("PASSWORD");
        signinPanel.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 80, 20));

        jPanel2.setBackground(new java.awt.Color(97, 212, 195));
        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel2.setForeground(new java.awt.Color(204, 204, 204));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        signin.setBackground(new java.awt.Color(97, 212, 195));
        signin.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        signin.setForeground(new java.awt.Color(255, 255, 255));
        signin.setText("SIGN IN");
        signin.setBorderPainted(false);
        signin.setContentAreaFilled(false);
        signin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signinActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(signin, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(signin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        signinPanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, -1, -1));

        getContentPane().add(signinPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, 430, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void signupEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signupEmailActionPerformed

    private void signupFnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupFnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signupFnameActionPerformed

    private void signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupActionPerformed
        email = signupEmail.getText();
        pass = new String(signupPass.getPassword());
        fname = signupFname.getText();
        lname = signupLname.getText();
        rpass = new String(signupRpass.getPassword());
        area = signupArea.getText();
        System.out.println(pass);
        System.out.println(rpass);
        
        if(pass == null ? rpass == null : pass.equals(rpass)){
            query = "insert into usertable(email_id, password, usertypeid, usertype, fname, lname, location) values('"+email+"', '"+rpass+"', 2, 'customer', '"+fname+"', '"+lname+"', '"+area+"')";
            System.out.println(query);
            
        ob.insertUser(query);
        }
        else{
            JOptionPane.showMessageDialog(null, "Invalid password!!!");
        }
       // System.out.println(query);
    }//GEN-LAST:event_signupActionPerformed

    private void signinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signinActionPerformed
        email = signinEmail.getText();
        pass = new String(signinPass.getPassword());
        usertype = userInfo.getSelectedItem().toString();
        result = ob.signIn(email, pass, usertype);
       // String cu = "Customer";
        //System.out.println(usertype);
        
       if(usertype.equals("Customer")){
          // System.out.println("lfafd");
                    customerInterface1 c = new customerInterface1();
                    this.setVisible(false);
                    c.setVisible(true);
                }
       else{
//           System.out.println("lfafd");
//                    customerInterface1 c = new customerInterface1();
//                    this.setVisible(false);
//                    c.setVisible(true);
       }
    }//GEN-LAST:event_signinActionPerformed

    private void signupPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signupPassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUpForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUpForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUpForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUpForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUpForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator21;
    private javax.swing.JSeparator jSeparator24;
    private javax.swing.JSeparator jSeparator25;
    private javax.swing.JSeparator jSeparator26;
    private javax.swing.JSeparator jSeparator27;
    private javax.swing.JSeparator jSeparator28;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JButton signin;
    private javax.swing.JTextField signinEmail;
    private javax.swing.JPanel signinPanel;
    private javax.swing.JPasswordField signinPass;
    private javax.swing.JButton signup;
    private javax.swing.JPasswordField signupArea;
    private javax.swing.JTextField signupEmail;
    private javax.swing.JTextField signupFname;
    private javax.swing.JTextField signupLname;
    private javax.swing.JPanel signupPanel;
    private javax.swing.JPasswordField signupPass;
    private javax.swing.JPasswordField signupRpass;
    private javax.swing.JComboBox<String> userInfo;
    // End of variables declaration//GEN-END:variables
}
